#!/usr/bin/env bash
# Fetch the sparse AOSP source/header quarry used by the foreign Innit build.
# The quarry is reproducible and must stay ignored by git.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
# shellcheck source=foreign/common.sh
source "$SCRIPT_DIR/common.sh"

usage() {
  cat <<EOF_USAGE
Usage: foreign/quarry.sh [command]

Commands:
  sync        Fetch/update sparse AOSP quarry. Default.
  status      Print quarry revisions.
  clean       Remove quarry directory.
  gitignore   Print the .gitignore fragment required by this build path.

Environment:
  AOSP_TAG      Android tag to quarry. Default: $AOSP_TAG
  QUARRY_DIR    Quarry destination. Default: $QUARRY_DIR

The script writes:
  foreign/config/quarry.lock

EOF_USAGE
}

clone_sparse() {
  local name="$1"
  local url="$2"
  local dest="$3"
  shift 3
  local paths=("$@")

  mkdir -p "$(dirname "$dest")"

  if [[ ! -d "$dest/.git" ]]; then
    log "cloning $name at $AOSP_TAG"
    git clone --filter=blob:none --no-checkout "$url" "$dest"
  else
    log "updating $name"
  fi

  git -C "$dest" remote set-url origin "$url"
  git -C "$dest" fetch --depth=1 origin "refs/tags/$AOSP_TAG:refs/tags/$AOSP_TAG" || \
    git -C "$dest" fetch --depth=1 origin "$AOSP_TAG"

  git -C "$dest" sparse-checkout init --cone >/dev/null
  if [[ ${#paths[@]} -eq 1 && "${paths[0]}" == "." ]]; then
    git -C "$dest" sparse-checkout disable >/dev/null || true
  else
    git -C "$dest" sparse-checkout set "${paths[@]}" >/dev/null
  fi
  git -C "$dest" checkout -f "$AOSP_TAG" >/dev/null
}

write_gitignore_fragment() {
  cat <<'EOF_GITIGNORE'
# Innit foreign-build quarry; reproducible, not source of truth.
/quarry/

# Innit foreign build outputs.
/out/

# Locally generated proto/shim material.
/foreign/generated/

# Machine-local build configuration.
/foreign/config/local.env
/foreign/config/abi-root.env
EOF_GITIGNORE
}

check_gitignore() {
  local gi="$REPO_ROOT/.gitignore"
  if [[ ! -f "$gi" ]]; then
    warn "no .gitignore at repository root; create one and include the fragment printed by: foreign/quarry.sh gitignore"
    return 0
  fi
  if ! grep -Eq '^/quarry/?$' "$gi"; then
    warn "$gi does not contain /quarry/; add the fragment printed by: foreign/quarry.sh gitignore"
  fi
}

sync_quarry() {
  ensure_repo_root
  refuse_android_product_env
  require_cmd git
  check_gitignore

  mkdir -p "$QUARRY_DIR"

  clone_sparse "system/core" \
    "https://android.googlesource.com/platform/system/core" \
    "$QUARRY_DIR/system/core" \
    libcutils \
    fs_mgr \
    liblogwrap \
    libmodprobe \
    libprocessgroup \
    libprocinfo \
    libsystem \
    property_service \
    bootloader_message

  clone_sparse "system/libbase" \
    "https://android.googlesource.com/platform/system/libbase" \
    "$QUARRY_DIR/system/libbase" \
    include

  clone_sparse "system/logging" \
    "https://android.googlesource.com/platform/system/logging" \
    "$QUARRY_DIR/system/logging" \
    liblog

  clone_sparse "system/vold" \
    "https://android.googlesource.com/platform/system/vold" \
    "$QUARRY_DIR/system/vold" \
    fscrypt \
    Utils.h

  clone_sparse "system/extras" \
    "https://android.googlesource.com/platform/system/extras" \
    "$QUARRY_DIR/system/extras" \
    ext4_utils

  clone_sparse "external/selinux" \
    "https://android.googlesource.com/platform/external/selinux" \
    "$QUARRY_DIR/external/selinux" \
    libselinux

  clone_sparse "external/tinyxml2" \
    "https://android.googlesource.com/platform/external/tinyxml2" \
    "$QUARRY_DIR/external/tinyxml2" \
    .

  clone_sparse "external/protobuf" \
    "https://android.googlesource.com/platform/external/protobuf" \
    "$QUARRY_DIR/external/protobuf" \
    src

  clone_sparse "external/libcap" \
    "https://android.googlesource.com/platform/external/libcap" \
    "$QUARRY_DIR/external/libcap" \
    libcap \
    libcap/include

  clone_sparse "external/avb" \
    "https://android.googlesource.com/platform/external/avb" \
    "$QUARRY_DIR/external/avb" \
    libavb

  write_lock
  log "quarry ready: $QUARRY_DIR"
}

write_lock() {
  local lock="$REPO_ROOT/foreign/config/quarry.lock"
  mkdir -p "$(dirname "$lock")"
  {
    printf '# Generated by foreign/quarry.sh. Commit this file, not quarry/.\n'
    printf 'AOSP_TAG=%s\n' "$AOSP_TAG"
    printf 'QUARRY_DIR=%s\n' "quarry/aosp-$AOSP_TAG"
    printf '\n'
    for repo in \
      system/core \
      system/libbase \
      system/logging \
      system/vold \
      system/extras \
      external/selinux \
      external/tinyxml2 \
      external/protobuf \
      external/libcap \
      external/avb
    do
      local path="$QUARRY_DIR/$repo"
      if [[ -d "$path/.git" ]]; then
        printf '%s=%s\n' "${repo//\//_}" "$(git -C "$path" rev-parse HEAD)"
      fi
    done
  } > "$lock"
}

status_quarry() {
  ensure_repo_root
  if [[ ! -d "$QUARRY_DIR" ]]; then
    die "quarry does not exist: $QUARRY_DIR"
  fi
  for d in "$QUARRY_DIR"/*/*; do
    [[ -d "$d/.git" ]] || continue
    printf '%-40s %s\n' "${d#$QUARRY_DIR/}" "$(git -C "$d" rev-parse --short=12 HEAD)"
  done
}

clean_quarry() {
  ensure_repo_root
  [[ "$QUARRY_DIR" == "$REPO_ROOT"/* ]] || die "refusing to remove quarry outside repo root: $QUARRY_DIR"
  rm -rf "$QUARRY_DIR"
  log "removed $QUARRY_DIR"
}

cmd="${1:-sync}"
case "$cmd" in
  sync) sync_quarry ;;
  status) status_quarry ;;
  clean) clean_quarry ;;
  gitignore) write_gitignore_fragment ;;
  -h|--help|help) usage ;;
  *) usage >&2; die "unknown command: $cmd" ;;
esac
